name: rspec

# Triggers the workflow on push or pull request events
on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: |
        sudo apt-get install libcairo2-dev
        bundle install --without gui
    - name: Run Rspec Tests
      run: rspec --format doc
